### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by IttoSanzzo** [zaftnotameni/creatania#13]
[crash-2023-06-14_14.11.35-fml.txt](https://github.com/zaftnotameni/creatania/files/11748865/crash-2023-06-14_14.11.35-fml.txt)

I think it must be an incompatibility with create 1.5.1... I think it's quite possible that just recompiling with the updated mod can fix it

edit: i tried to do it, changing the version used to compile with create.1.5.1.b-285, but no good... they probably made changes in certain classes, i saw that especially in KineticTileEntity, and some others, the which breaks the build as is... unfortunately it looks like a fix would be more work... good luck

**Comment by IttoSanzzo** [comment]
...for me. I took some time off, and fixed all of the Create class changes, and the other changes needed with those. The mod is 99.999% functional as it should be. The only difference is regarding ScrollValue events for mana engines. That's because 1.5.1.b changes how selectors work to draggable bars instead of scroll events. In that way, I kind of "got it in a way that worked", but I wouldn't say perfect, and therefore, the mod is 99.999%. If you want, Zaftnotameni, I can send the src with the updates, and you can take your time to check it, just don't forget to change the version of create in gradlew to compile xD

**Comment by ClaudiusMinimus** [comment]
Thanks for fixing this! I might be able to do a merge if you submit a pull request. My job in the project was modeling, graphics, ponder scenes, and documentation. I think I can compile it, but would you like to be part of the team? Zaftnotameni has not been heard from since March. If you are interested, please contact me on [CM's World Discord](https://discord.com/invite/jXrx4Tu) When onboarding, select the Creatania role - _others if interested_.
Thank you,
CM (aka ClaudiusMinimus)
