### ISSUE TITLE
Optional dependencies and Kotlin's usefulness ?

### ISSUE THREAD

**Issue by Xenxia** [zaftnotameni/creatania#16]
Hello, thank you for this mod

I wanted to know if ponderJS and KubeJS were only used to give the user the possibility of adding content. If so, wouldn't it be possible to make the addition of these modes optional when they're not needed?

What is the use of Kotlin? Can it be rewritten from Java to Kotlin or from Kotlin to Java, and can it be used to add or simplify functionality?

All this to know if a reduction of mode dependencies is planned? because it's a bit constraining to have 4 library modes for 1 gameplay mode when you have a big mode pack.

Thank you for your answers.

**Comment by ClaudiusMinimus** [comment]
Hi Xenxia,

Thank you for letting us know about your enjoyment with Creatania. I am still very excited to continue developing this mod. As you may have noticed, Zaft, the main developer has disappeared and we would welcome his return. I have extended an invitation for others to join in the development during Zaft's absence. Two have answered that invitation. They both admit very limited Java experience but are willing to try and help. My son, who is a software engineer on the Amazon AWS team has offered to mentor and help them as needed. As such, the invitation for an experienced Java developer is still open. My role is making the models, artwork, textures, ponder scenes, and documentation. 

With the above said, I will attempt to answer your questions:

> I wanted to know if ponderJS and KubeJS were only used to give the user the possibility of adding content. If so, wouldn't it be possible to make the addition of these modes optional when they're not needed?

Zaft started making the ponder scenes and in fact, made some of the scenes in the mod, but I took over and used PonderJS exclusively. I have no Java experience but was able to make some nice scenes only because of KubeJS and PonderJS.

> What is the use of Kotlin? Can it be rewritten from Java to Kotlin or from Kotlin to Java, and can it be used to add or simplify functionality?

If I understood correctly, Kotlin was added to simplify the coding process, which I have no experience with. I would invite any suggestions and if you are an experienced developer with Java or Kotlin and want to help, please join my [CM's World Discord](https://discord.com/invite/jXrx4Tu) and I will invite you to the Creatania development team channels. 

> All this to know if a reduction of mode dependencies is planned? because it's a bit constraining to have 4 library modes for 1 gameplay mode when you have a big mode pack.

We had talked about having Zaft convert my ponder scenes once we felt the mod was complete, and I am still open to it - which will remove the PonderJS and KubeJS dependencies. As mentioned, I am not a Java developer and I am very interested to discuss your suggestions,

In my mind there are two huge deficiencies, which I hope will soon be addressed:
1. Porting to 1.19.2 and then 1.20.x
2. Porting to Fabric. Creatania was inspired during planning and development for my [Create Conquest Arcane](https://legacy.curseforge.com/minecraft/modpacks/create-conquest-arcane) (CCA) modpack which was originally in 1.18.2 Forge. Unfortunately, I had to switch the pack to Fabric due to [Conquest Reforged](https://legacy.curseforge.com/minecraft/mc-mods/conquest-reforged) (a foundational mod in CCA) switching to Fabric. Therefore, Fabric is a priority so I can add Creatania back to CCA.

I thank you again for your interest in Creatania and look forward to hearing from you soon.
CM (aka ClaudiusMinimus)
[CM's World Discord](https://discord.com/invite/jXrx4Tu)
[ClaudiusMinimus Projects](https://legacy.curseforge.com/members/claudiusminimus/projects)

**Comment by Xenxia** [comment]
Thank you for your answers :)

I didn't know that the main developer had "disappeared".
I'm not an experienced Java developer, but I've already worked on Minecraft plugins and I wanted to try my hand at modding (the higher levels). If you'd like me to, I'd be happy to help.
